### ISSUE TITLE
Entities do not get removed upon removal of the integration

### ISSUE THREAD

**Issue by balk77** [koenhendriks/ha-button-plus#25]
It seem that entities do not get removed upon removal of the integration
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1246, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity 'text.label_btn_45a424_0' cannot be added a second time to an entity platform
```

**Comment by balk77** [comment]
maybe it was a leftover from an earlier attempt to install, before HACS. Now they do get removed.
