### ISSUE TITLE
Unable to add Button+ to integration

### ISSUE THREAD

**Issue by ruudvddries** [koenhendriks/ha-button-plus#63]
When adding the integration to HA and setting up the initial config I always get a message 'Failed to set up' when I try to fetch my button+ through the button.plus website.

I have uploaded the current config to the button.plus website.

What am I missing?

The log gives me this error:

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 22:14:41 (9 occurrences)
Last logged: 22:50:27

Error setting up entry btn_4674c0 for button_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/button_plus/__init__.py", line 26, in async_setup_entry
    device_configuration: DeviceConfiguration = DeviceConfiguration.from_json(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/button_plus/button_plus_api/model.py", line 259, in from_json
    data = json.loads(json_data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by koenhendriks** [comment]
I recommend to use the the direct IP approach. 

The feature to import from the button.plus website hasn't been updated with the latest changes in the configuration json structure. The feature will be removed before 1.0 anyway. 

I've only created it because I started developing the integration before I actually had the physical device and this way I could use the emulator to start testing.
