### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Rangandii** [koenhendriks/ha-button-plus#70]
When i try to setup the button+ in home assistant, I get this error.

`Logger: custom_components.button_plus.config_flow
Quelle: custom_components/button_plus/config_flow.py:123
Integration: Button+ ([Dokumentation](https://github.com/koenhendriks/ha-button-plus), [Probleme](https://github.com/koenhendriks/ha-button-plus/issues))
Erstmals aufgetreten: 00:00:38 (4 Vorkommnisse)
Zuletzt protokolliert: 00:33:17

button_plus Exception in login : 'largedisplay' - traceback: Traceback (most recent call last): File "/config/custom_components/button_plus/config_flow.py", line 98, in async_step_manual device_config: DeviceConfiguration = ModelDetection.model_for_json( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ json_config ^^^^^^^^^^^ ) ^ File "/config/custom_components/button_plus/button_plus_api/model_detection.py", line 15, in model_for_json return DeviceConfiguration.from_dict(data) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ File "/config/custom_components/button_plus/button_plus_api/model_v1_12.py", line 182, in from_dict info=Info.from_dict(data["info"]), ~~~~~~~~~~~~~~^^^^^^^^^^^^^^ File "/config/custom_components/button_plus/button_plus_api/model_v1_12.py", line 39, in from_dict large_display=data["largedisplay"], ~~~~^^^^^^^^^^^^^^^^ KeyError: 'largedisplay'
button_plus Exception in login : 'largedisplay' - traceback: Traceback (most recent call last): File "/config/custom_components/button_plus/config_flow.py", line 98, in async_step_manual File "/config/custom_components/button_plus/button_plus_api/model_detection.py", line 15, in model_for_json File "/config/custom_components/button_plus/button_plus_api/model_v1_12.py", line 182, in from_dict File "/config/custom_components/button_plus/button_plus_api/model_v1_12.py", line 39, in from_dict KeyError: 'largedisplay`

**Comment by DobnDiegoGER** [comment]
same problem. If I enter single device manually

**Comment by DR-Apples** [comment]
I tried to setup the Button+ and got the same error in the logs while setting it up manually. 

Setting the button+ up via the user/pass combination gives the following error:


```
Logger: homeassistant.config_entries
Bron: config_entries.py:635
Eerst voorgekomen: 16:39:28 (2 gebeurtenissen)
Laatst gelogd: 16:39:40

Error setting up entry wk1 for button_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/button_plus/__init__.py", line 29, in async_setup_entry
    device_configuration: DeviceConfiguration = ModelDetection.model_for_json(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/button_plus/button_plus_api/model_detection.py", line 9, in model_for_json
    data = json.loads(json_data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```


Used setup: 
Home Assistant Core: 2024.11.1
Home Assistant Operating System: 13.2

**Comment by P-Storm** [comment]
@Rangandii @DobnDiegoGER @DR-Apples what versions are you using? If you are using the newest 2.0 firmware I think everything got broken. This shouldn't be a problem because the MQTTDiscovery should auto detect this. Some things that 

In the trace that I see

```python
  File "/config/custom_components/button_plus/button_plus_api/model_detection.py", line 9, in model_for_json
    data = json.loads(json_data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
```

This shows that the json it reads into itself is not valid or something weird? Again supports the firmware 2.0 problem.

@koenhendriks if I'm not mistaken the component is deprecated with the MQTT discovery, is this the case? And if so, maybe make an good old big warning on the homepage :). (maybe even make a release that if it sees version >= 2.0 that the component shows a error with help description).


I saw:

1. The dashboard served is not complete (I thought problems with repeating button events)
2. Other then default config is disrupting the auto discovery, possible to fix with resetting the device.

**Comment by DR-Apples** [comment]
@P-Storm, yes, correct. I am running version 2.0.0

**Comment by P-Storm** [comment]
> @P-Storm, yes, correct. I am running version 2.0.0 I expect @Rangandii and @DobnDiegoGER do also run V2.0.0 as the error is the same.

Then the best course of action is to use the MQTT discovery for Home Assistant. Best to do is to reset everything, remove this custom component and use it without. Because the auto discovery is in Home Assistant, the future of this is unclear.
